services:
  nestapp:
    image: luisitotester/nest-demo:latest
    ports:
      - "3001:3000"
    env_file:
      - .env.development
    depends_on:
      - postgresdb
    networks:
      - networkNest

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development
    networks:
      - networkNest

volumes:
  pgdata:

networks:
  networkNest:
    driver: bridge