version: "3.9"

services:
  nestapp:
    build: luisitotester/nest-demo_latests:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    depends_on:
      - postgresdb

  postgresdb:
    image: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  pgdata: